/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommandPalette: typeof import('./src/components/navigation/Command-Palette/CommandPalette.vue')['default']
    CommandPaletteGroup: typeof import('./src/components/navigation/Command-Palette/CommandPaletteGroup.vue')['default']
    RouteLocationRaw: typeof import('vue-router')['RouteLocationRaw']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./src/components/elements/Accordion/UAccordion.vue')['default']
    UAlert: typeof import('./src/components/elements/Alert/UAlert.vue')['default']
    UAvatar: typeof import('./src/components/elements/Avatar/UAvatar.vue')['default']
    UAvatarGroup: typeof import('./src/components/elements/Avatar/UAvatarGroup.vue')['default']
    UBadge: typeof import('./src/components/elements/Badge/UBadge.vue')['default']
    UButton: typeof import('./src/components/elements/Button/UButton.vue')['default']
    UButtonGroup: typeof import('./src/components/elements/Button/UButtonGroup.vue')['default']
    UCard: typeof import('./src/components/layouts/Card/UCard.vue')['default']
    UCheckbox: typeof import('./src/components/forms/Checkbox/UCheckbox.vue')['default']
    UContainer: typeof import('./src/components/layouts/Container/UContainer.vue')['default']
    UContextMenu: typeof import('./src/components/overlays/ContextMenu/UContextMenu.vue')['default']
    UDropdown: typeof import('./src/components/elements/Dropdown/UDropdown.vue')['default']
    UFormGroup: typeof import('./src/components/forms/FormGroup/UFormGroup.vue')['default']
    UIcon: typeof import('./src/components/elements/Icon/UIcon.vue')['default']
    UInput: typeof import('./src/components/forms/Input/UInput.vue')['default']
    UKbd: typeof import('./src/components/elements/Kbd/UKbd.vue')['default']
    ULink: typeof import('./src/components/elements/Link/ULink.vue')['default']
    UModal: typeof import('./src/components/overlays/Modal/UModal.vue')['default']
    UNotification: typeof import('./src/components/overlays/Notification/UNotification.vue')['default']
    UNotifications: typeof import('./src/components/overlays/Notification/UNotifications.vue')['default']
    UPagination: typeof import('./src/components/navigation/Pagination/UPagination.vue')['default']
    UPopover: typeof import('./src/components/overlays/Popover/UPopover.vue')['default']
    URadio: typeof import('./src/components/forms/Radio/URadio.vue')['default']
    URange: typeof import('./src/components/forms/Range/URange.vue')['default']
    USelect: typeof import('./src/components/forms/Select/USelect.vue')['default']
    USelectMenu: typeof import('./src/components/forms/SelectMenu/USelectMenu.vue')['default']
    USkeleton: typeof import('./src/components/layouts/Skeleton/USkeleton.vue')['default']
    USlideover: typeof import('./src/components/overlays/Slideover/USlideover.vue')['default']
    UTable: typeof import('./src/components/data/Table/UTable.vue')['default']
    UTabs: typeof import('./src/components/navigation/Tabs/UTabs.vue')['default']
    UTextarea: typeof import('./src/components/forms/Textarea/UTextarea.vue')['default']
    UToggle: typeof import('./src/components/forms/Toggle/UToggle.vue')['default']
    UTooltip: typeof import('./src/components/overlays/Tooltip/UTooltip.vue')['default']
    UVerticalNavigation: typeof import('./src/components/navigation/VerticalNavigation/UVerticalNavigation.vue')['default']
  }
}
