export enum Components {
  UAlert = 'UAlert',
  UAccordion = 'UAccordion',
  UAvatar = 'UAvatar',
  UAvatarGroup = 'UAvatarGroup',
  UBadge = 'UBadge',
  UButton = 'UButton',
  ULink = 'ULink',
  UButtonGroup = 'UButtonGroup',
  UDropdown = 'UDropdown',
  UIcon = 'UIcon',
  UInput = 'UInput',
  UKbd = 'UKbd',
  UTextarea = 'UTextarea',
}
