export enum Components {
  UAlert = 'UAlert',
  UAccordion = 'UAccordion',
  UAvatar = 'UAvatar',
  UAvatarGroup = 'UAvatarGroup',
  UBadge = 'UBadge',
  UButton = 'UButton',
  UCommandPalette = 'UCommandPalette',
  UCommandPaletteGroup = 'UCommandPaletteGroup',
  UCheckbox = 'UCheckbox',
  ULink = 'ULink',
  UButtonGroup = 'UButtonGroup',
  UDropdown = 'UDropdown',
  UFormGroup = 'UFormGroup',
  UIcon = 'UIcon',
  UInput = 'UInput',
  UKbd = 'UKbd',
  URadio = 'URadio',
  URange = 'URange',
  USelect = 'USelect',
  USelectMenu = 'USelectMenu',
  UTable = 'UTable',
  UTextarea = 'UTextarea',
  UToggle = 'UToggle',
  UVerticalNavigation = 'UVerticalNavigation',
}
